root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/bff-service ./cmd/server"
  
  bin = "./tmp/bff-service"
  
  include_ext = ["go", "tpl", "tmpl", "html"]
  
  exclude_dir = ["tmp", "vendor", "testdata"]
  
  exclude_regex = ["_test.go"]
  
  delay = 1000
  
  # Stop on error
  stop_on_error = true
  
  # Log file
  log = "tmp/build-errors.log"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true