global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
        - 'auth-service:8001'
        - 'ios_user_service:8002'
        - 'ios_bff_service:8000'
        - 'ios_realtime_service:8080'